spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/secretfriends
    username: secretfriends
    password: secretfriends

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true

logging:
  level:
    org:
      springframework: info
      dallili: debug
